version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=event-manager-dev-secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production database (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: eventmanager
      POSTGRES_USER: eventmanager
      POSTGRES_PASSWORD: eventmanager123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["production"]

volumes:
  postgres_data:

networks:
  default:
    name: event-manager-network